### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jvoorhis** [richarcher/Hatjitsu#5]
This project currently has no license. Can you please add a license file?

Thank you,

Jeremy

**Comment by KendallPark** [comment]
+1

**Comment by bd808** [comment]
@joergd and @richarcher I love your tool and have used it on several teams to facilitate estimation during sprint planning. While setting up a new instance of the service today I realized that the project does not have a published license. I was hoping that I could convince you to select and apply some[ OSI approved license](https://en.wikipedia.org/wiki/Open_Source_Initiative) to the project so that myself and others who are running copies of it could do so with a clean conscience.

**Comment by richarcher** [comment]
Good call. Done.
